# Generated by Django 5.1.4 on 2025-01-10 17:50

import api.Models.ProyectoModel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuario normal')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('estado', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('participantes', models.IntegerField(validators=[api.Models.ProyectoModel.validar_participantes])),
                ('usuarios', models.ManyToManyField(related_name='proyectos', to='api.user')),
            ],
        ),
    ]
