# Generated by Django 5.1.4 on 2025-01-08 17:34

import api.Models.ProyectoModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=180)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('estado', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('participantes', models.IntegerField(validators=[api.Models.ProyectoModel.validar_participantes])),
            ],
        ),
    ]
