# Generated by Django 5.1.4 on 2025-01-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='usuarios',
            field=models.ManyToManyField(related_name='proyectos', to='api.user'),
        ),
    ]
